spring:
 datasource:
  url: jdbc:mysql://localhost:3306/ems
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
    dialects: org.hibernate.dialect.MySQL8Dialect