
spring:
 application:
  name: EMPLOLYEE-GATEWAY


server:
 port: 8084


eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:9091/eureka


#instance:
# hostname: localhost


zuul:
 prefix: /logical
 routes:
    dummyservices:
     path: /url/**
     service-id: EMPLOLYEE-SEARCH
#zuul:
# routes:
#  employeeUI: EMPLOLYEE-SEARCH-DASHBOARD






